### ISSUE TITLE
Update base docker image for CI

### ISSUE THREAD

**Issue by andrerenard** [kotekan/kotekan#1017]
It looks like the AMD based Ubuntu/ROCm image we are using for the CI might no longer be supported (AMD has removed some files from their public repo).   For now it seems to be happy just using the cached image, but this will become a problem at some point (and prevents us from updating the image).

**Comment by jbmertens** [comment]
#1109 addresses this in the 18.04 build, but there are some outstanding issues in the 22.04 build. I'll create separate issues for those items.
