### ISSUE TITLE
Random persistent failures of `test_eigenvis.py` 

### ISSUE THREAD

**Issue by andrerenard** [kotekan/kotekan#1034]
For reasons I don't yet understand `test_eigenvis.py` has been failing the `test_basic()` test with the following error when run in github actions.   It doesn't happen with every PR, but once it happens re-runs of the test don't resolve the problem.  The failure signature always looks like this, always with the same values: 
```
=================================== FAILURES ===================================
__________________________________ test_basic __________________________________
[gw1] linux -- Python 3.7.9 /usr/bin/python3.7
tmpdir_factory = TempdirFactory(_tmppath_factory=TempPathFactory(_given_basetemp=PosixPath('/tmp/pytest-of-root/pytest-0/popen-gw1'), _...pluggy._tracing.TagTracerSub object at 0x7f9ffdc35c10>, _basetemp=PosixPath('/tmp/pytest-of-root/pytest-0/popen-gw1')))
    def test_basic(tmpdir_factory):
        params = default_params
        num_elements = params["num_elements"]
        expected_evec_phase_fact = np.exp(1j * np.arange(num_elements))
        eigen_data = run_eigenvis(tmpdir_factory)
        for frame in eigen_data:
            largest_eval = frame.eval[0]
            largest_evec = frame.evec[:num_elements]
            assert abs(largest_eval - num_elements) / num_elements < 1e-6
            assert np.allclose(largest_evec / largest_evec[0], expected_evec_phase_fact)
            assert np.allclose(abs(largest_evec), 1 / np.sqrt(num_elements))
            zero_eval = frame.eval[1]
            assert zero_eval / num_elements < 1e-6
>           assert frame.erms < 1e-6
E           assert array([1.2018842e-06], dtype=float32) < 1e-06
E            +  where array([1.2018842e-06], dtype=float32) = <kotekan.visbuffer.VisBuffer object at 0x7f9ff1944450>.erms
test_eigenvis.py:68: AssertionError
```
It's been hard to track down, since I cannot reproduce it on my local system.   The test also doesn't seem to involve any random number generation (unless I'm missing some randomization component in the eigenvalue solver).   This makes me think it might be some kind of memory problem, with something not initializing correctly when run in the github actions environment.

**Comment by jrs65** [comment]
Yeah, this is definitely not one of the random statistical tests so it should be entirely deterministic. I wonder if the underlying linear algebra libraries have got changed somehow. Has Github updated its ubuntu-latest image?

**Comment by andrerenard** [comment]
> Has Github updated its ubuntu-latest image?

I thought this might be it, but then one of my failing PRs passed after just retrying a few times.   Perhaps there is different hardware underlying the GitHub VMs that changes the versions?   I know we've run into issues with AVX in that respect.

**Comment by jrs65** [comment]
Yeah, there's a whole mix of hardware generations on the Azure instances it uses, and something like OpenBLAS will dynamically change the computational methods it uses depending on the instructions available.

One thing that *might* work would be trying to pin the set of kernels that OpenBLAS uses. You can do that via an environment variable (https://github.com/xianyi/OpenBLAS/wiki/Faq#choose_target_dynamic). I would just select the kernel corresponding to the oldest microarchitecture that you'll see on one of the Azure runners.

**Comment by jbmertens** [comment]
Hi @jrs65 - this test passes when I run locally, on a local 18.04 image, and consistently passes on 22.04. Do you think your 
suggestion above is worth trying, or something easier like changing the tolerance of the test, or just running the test on 22.04 only?

**Comment by jbmertens** [comment]
Marking as resolved per #1129

**Comment by jrs65** [comment]
I'm reopening this because I don't think it's been properly fixed.

**Comment by jbmertens** [comment]
Re-closing per #1132
