### ISSUE TITLE
KotekanMaster August Updates

### ISSUE THREAD

**Issue by shinybrar** [kotekan/kotekan#124]
# Updates
  - [x] __Calibration Broker Federation__
    Once the calibration broker updates the endpoints shown below KotekanMaster will federate this information to (see below for details):
    - Kotekan Nodes
    - Receiver Nodes
  - [x] Pulsar endpoints will now be broadcasted on `pulsar_timing_ops` slack channel
  - km-cli
    - [x] `ew_spacing` and `northmost_beam` parameters configuration and status support
    - [x] `bad_inputs` and `calibration_dir` parameters and status support
  - Better tracking of restart times.

# Bug Fixes
  - [x] Auto-Restart Functionility
  - [x] km-cli
    - [x] Make `blacklist/whitelist` functionality similar to `cctl` to  accept both upper and lower-case node names as inputs.

# Testing Status
  - [x] km-cli
  - [x] New federation endpoints
  - [x] Pulsar Slack
  - [ ] Restart Functionality
  - [ ] Documentation

# New Endpoints
### POST Message
```
curl
-d '{ 
  "tag": <HASH>, 
  "start_time": <C_TIME>, 
  "correlator_bad_inputs": <ARRAY>, 
  "cylinder_bad_inputs": <ARRAY> }'
-X POST
-H "Content-Type: application/json"
http://KOTEKAN-MASTER:PORT/update-bad-inputs
```
### Federation
Upon a successful POST to `update-bad-inputs` KotekanMaster will perform the following federation actions:
  - Update `/bad_inputs` endpoint on each Kotekan node.
```
-d '{ 
  "tag": <HASH>, 
  "start_time": <C_TIME>, 
  "bad_inputs": <CYLINDER_ORDERED_BAD_INPUTS> }'
-X POST
-H "Content-Type: application/json"
http://KOTEKAN_NODE/gpu/gpu_[ 0-3 ]/update_bad_inputs
```
  - Update `/num_bad_inputs` endpoint on each kotekan node.
```
-d '{ 
  "tag": <HASH>, 
  "start_time": <C_TIME>, 
  "num_bad_inputs": <INT> }'
-X POST
-H "Content-Type: application/json"
http://kotekan_node/gpu/gpu_[0-3 ]/update_num_bad_inputs
```

  - Update a `bad_inputs` endpoint on each `Receiver Node`
```
WIP
```
  
### Format of POST
``` 
-d '{
  "tag": <HASH>, 
  "start_time": <C_TIME>, 
  "calibration_dir": 'hostname:/full/path/to/calibration/dir/'}'
-X POST
-H "Content-Type: application/json"
http://KOTEKAN-MASTER-NODE/update-calibration-dir
```
### Federation
Upon a successful POST to `update-calibration-dir` KotekanMaster will perform the following federation actions:
  - Update a `calibration-dir` endpoint on all Receiver Nodes.

**Comment by andrerenard** [comment]
This is an old ticket that was mostly handled by moving to `coco`
