### ISSUE TITLE
Add metrics for file types being written

### ISSUE THREAD

**Issue by nritsche** [kotekan/kotekan#214]
Add a prometheus metric for each file type
- ben_hk
- chime26m_corr
- chimeN2_corr
- chime_rawadc
- chimecal_corr
- chimestack_corr
- chimetiming_corr
- mingun_weather

that says if it is being written or not. This is so that the slack alerts for alpenhorn not registering files ([here](https://github.com/CHIMEFRB/frb_ansible/issues/5)), can be changed to not be triggered when kotekan is configured to not write a certain file type.

**Comment by andrerenard** [comment]
I think this was done. We do see the types of data products being written in the grafana overview page.  @nritsche please reopen if I'm wrong.
