### ISSUE TITLE
Add updatable config to turn on/off writing of visWriters

### ISSUE THREAD

**Issue by jrs65** [kotekan/kotekan#295]
We need to be able to turn visWriters on and off without having to restart kotekan every time. I think this fits well within the updatableConfig framework (as opposed to a specific REST endpoint). I'm a little concerned by the fact that you need to pass *all* possible config in an update, but I think that might be better as visWriter is fetching more metadata from the dM now.

**Comment by andrerenard** [comment]
This is closed by #345
