### ISSUE TITLE
better balance between baseline compression threads

### ISSUE THREAD

**Issue by nritsche** [kotekan/kotekan#350]
The 2 threads of the baselineCompression stage are not processing frames at the same speed. One of them processes even frames, the other processes uneven ones. This leads to one of them congesting, the other one starving.
```
Buffer visbuf_10s_gain, status: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Buffer visbuf_10s_stack, status: _X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X__
/buffer_recv/26m/instance: No free buffer frames, dropping data from 10.1.2.16
```

I propose they should share one frame ID instead.

**Comment by jrs65** [comment]
Closing as duplicate
