### ISSUE TITLE
Double counting RFI data sample loss (over normalization)

### ISSUE THREAD

**Issue by andrerenard** [kotekan/kotekan#352]
In the `2018.12` deployment it was discovered that when packets are lost due to network/system load levels, and there was RFI flagged on the same time period in which the packet loss happened, then the number of lost samples is double counted.  This means the amount of renormalization applied ends up being too high. 

The fix should be fairly easy, but because of when it was discovered in the `2018.12` deployment, it didn't make it into that release.   Instead for `2018.12` the RFI zeroing is disabled by default.

**Comment by nritsche** [comment]
Closed by #418
