### ISSUE TITLE
RFI zeroing seems to be giving incorrect lost sample counts

### ISSUE THREAD

**Issue by jrs65** [kotekan/kotekan#354]
When RFI zeroing is turned on the lost sample count seems to be getting set incorrectly. Evidence for this is slightly indirect, but what seems to happen is that the `fpga_total` within `visMetadata` gets set to values larger than `fpga_length` which can only happen when the lost sample count is negative. According to Andre the values are quite similar to what you'd expect if we'd overflowed a 32 bit int.

Plots coming soon....

**Comment by jrs65** [comment]
This is not quite the same issue as #352 though might be related. This one is way worse.

**Comment by jrs65** [comment]
![image](https://user-images.githubusercontent.com/695206/50058076-5c076000-0141-11e9-9697-6ab3f8482c24.png)

In the plot above I've tried to extract the lost sample fraction from some of the stacked data on 16th November. The orange points are the "normal" ones, some of them have fraction 1, which means they were entirely flagged out, the blue one are the bad ones. For those the lost sample value was actually negative (I've negated it, before taking the log), and you can see that the values are huge (> 10^3 in many cases). This will cause those effect frames to get renormalised to ~zero.

If I make the same plot before the RFI zeroing was turned on (Nov 1st), you basically get only the orange (i.e. good points), and the values are all a lot lower.
![image](https://user-images.githubusercontent.com/695206/50058155-5d855800-0142-11e9-888b-f4f4adb651f6.png)

**Comment by andrerenard** [comment]
This was fixed in #418
