### ISSUE TITLE
Balancing with multithreaded recv processes

### ISSUE THREAD

**Issue by jrs65** [kotekan/kotekan#355]
In the two multithreaded receiver processes (`applyGains`, `baselineCompression`) we distribute the work to the threads by round robin assigning frames too them. This has an issue that if one thread runs slower than the other one half of the buffer can fill (alternating frames) without it looking like a problem, this causes the whole system to slow down. At the moment this seems to be the dominant cause of frames being dropped in the recv system, so it needs to be fixed.

One option that Rick suggested is that each thread would just claim the next available frame rather than only the next alternating frame. To make this work you need a single `frameID` for all threads, and at the start of the main loop you would lock the frame ID, make a copy and increment it, unlock and then process the frame using the copied value.

**Comment by jrs65** [comment]
From @nritsche:

> The 2 threads of the baselineCompression stage are not processing frames at the same speed. One of them processes even frames, the other processes uneven ones. This leads to one of them congesting, the other one starving.
> ```
> Buffer visbuf_10s_gain, status: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> Buffer visbuf_10s_stack, status: _X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X__
> /buffer_recv/26m/instance: No free buffer frames, dropping data from 10.1.2.16
> ```
> I propose they should share one frame ID instead.

**Comment by jrs65** [comment]
Closing #350 as duplicate (this one was longer!)

**Comment by andrerenard** [comment]
Closed by #379
