### ISSUE TITLE
Calibration hot fix

### ISSUE THREAD

**Issue by jrs65** [kotekan/kotekan#377]
A meta issue to track the planned calibration hot fix. (Tagging interested parties: @mondana @mattadobbs @kvand @andrerenard @cherryng @ssiegelx @nritsche)

The primary change we want to deploy is the change to the eigendecomposition process. As discussed on Wednesday, I believe that the new algorithm works well and fits within the timing budget, but I’m doing testing now to see how it performs on data outside of transits. Hopefully I’ll have an update about that at the calibration call tomorrow. Beyond testing, I need to integrate a few changes to the masking of baselines within it, but I don’t expect those changes will take long. This update will also require a small change to the calibration broker so that it knows when the solutions converged and when they didn’t. Currently tracked in #376

I think we also want to deploy a few other small changes. Those that I can think of are:

- Threading fixes #379 (@nritsche). Fixes to the threading within the recv process to remove a source of dropped packets. Rick has written this already, though I don’t think it’s been widely tested.

- Update validation fix #369  (@nritsche). Fixes a bug that causes updates to be validated incorrectly, that leads to issues when changing the pulsar gating. I think this is a straightforward and low risk change.

- Pulsar timing fix (@cherryng). There was some discussion about whether we should fix the final aspect of the pulsar timing issues in this hot fix. I can't remember the details. @cherryng if you're still thinking of doing this please tag any tracking issue/PR here. 

One maybe is:

- Acquisition closing fix (#364). This should be a simple fix, but it doesn't actually exist yet. And maybe there's too many other changes, this is mostly an annoyance (@tristpinsm can you live without this one?)

Original plan for the update was the end of this week. I think that schedule is still plausible, but we should know more by the end of tomorrow.

**Comment by jrs65** [comment]
P.S. I'll create a board for this one tomorrow. Just thought it's easier to keep discussion here.

**Comment by tristpinsm** [comment]
As far as I'm concerned, the acquisition closing bug is inconvenient but not really holding anything back. To get at some of the gated acquisitions I might end up generating a few short junk acquisitions. So if we'd rather not pile this on top of the already sizeable chunk of updates I won't object.

**Comment by andrerenard** [comment]
Are we thinking Thursday or Friday for deploying this?

**Comment by jrs65** [comment]
Not sure yet. Ideally Thursday. @mondana any thoughts?

**Comment by mondana** [comment]
@jrs65 Thursday sounds good. Has @cherryng confirmed what the pulsar-timing fix is?

**Comment by andrerenard** [comment]
There is a fix for the pulsar-timing problem: #380 , @cherryng posted it yesterday.   However before we can apply it we need to make sure @arunnaidu123 can support the change on his end.   My feeling is that we stay with Thursday, and if we get the ok we'll merge it, if not it'll wait for the next deployment.

**Comment by mondana** [comment]
@ssiegelx would relevant calibration-broker changes be ready by Thursday?

**Comment by ssiegelx** [comment]
@mondana The calibration broker changes are ready now.

I will deploy them in 30 minutes or so (after the CygA transit).   That way we can test the changes with sources that are not currently being used to calibrate.

**Comment by andrerenard** [comment]
This hotfix has already happened. Closing.
