### ISSUE TITLE
Better handling of missing FRB nodes

### ISSUE THREAD

**Issue by cubranic** [kotekan/kotekan#449]
The FRB subsystem (L0, specifically, the `frbNetworkProcess` class) uses the ordering of destination (L1) nodes in the config key `frb.buffer_read.L1_node_ips` to determine which beams to send where. In tandem, L1 nodes include the expected beam ids as part of their configuration, and depend on receiving the correct beam to function properly.

This implicit dependency between the two systems' configs makes it difficult to change the list of L1 nodes that should receive the L0 traffic, because it also requires a change to the L1 config and a restart of that system. (It appears that other parts of the FRB, such as FRB-master, also depend on the current beam-node mapping.) 

On the other hand, the Kotekan cluster experienced difficulties (cluster-wide ARP storms, as well as traffic delays) when trying to send to L1 nodes that are powered off. (Such as those with faulty hardware). Being able to stop sending of L0 data to such nodes is then a useful feature, especially if it could be done dynamically.

There are several ways in which this could be done, so here is a few ideas just to start the discussion:
- handle having "null" entries in the `L1_node_ips` list, allowing disabling of sending to missing nodes without changing the beam -> L1 mapping.
- provide a REST endpoint to dynamically change the L1 recipient list, or temporarily disable sending to arbitrary nodes while still keeping them in the iteration list (allow also enabling them the same way)
- keep a (beam -> L1) map in the L0 config, instead of a simple list that’s iterated through round-robin
- have an initial or periodic check (ping) of L1 recipients and disable sending to ones that are down

**Comment by andrerenard** [comment]
This would be a very good change to have!    I think the best setup would be a periodic check of the L1 nodes.  That leads to the minimal amount of human intervention, has less risk of us forgetting something, and reacts more quickly to dynamic changes.  If we do this, then it would be good for kotekan to also have an endpoint that allow us to query the L1 nodes it is currently unable to reach.

**Comment by cubranic** [comment]
For the purpose of L1 development, it would also be extremely useful to be able to duplicate beams and send them to multiple nodes. It seems like it could be had almost for free if we get the config handling/logic right.
