### ISSUE TITLE
Determine if the network transmission codes for FRB/Pulsar will support missing frames

### ISSUE THREAD

**Issue by andrerenard** [kotekan/kotekan#463]
See #462, we would like to support missing frames.  This means the network code will stop getting frames for a small block of frames and need to restart.  It's not clear if the flow control code will be able to recover from this kind event or not.   We need to determine that, and then if required update the flow control code to support missing frames from the Pulsar/FRB postProcess stages.

**Comment by jrs65** [comment]
Answer is no.
