### ISSUE TITLE
roundtripping floats in nlohmann::json::dump()

### ISSUE THREAD

**Issue by nritsche** [kotekan/kotekan#477]
Some floats in the running config round trip when putting them through `nlohmann::json::dump()` or `.get<double>()`, e.g.:
```
105.62744 -> 105.62744000000001
4210612934.6611814 -> 4210612934.6611815
```

When producing a hash of the running config, kotekan uses the `dump()` function and for that reason the hash mismatches with the python implementation in https://github.com/chime-experiment/coco that checks against it. This probably was one of the causes for desyncs&restarts with kotekan_master. At the momtent it leads to `coco` making unnecessary slow checks against the actual running config.

One solution could be 
```
std::vector<std::uint8_t> v_msgpack = json::to_msgpack(_json);
MD5((const unsigned char*)v_msgpack.data(), v_msgpack.size(), md5sum);
```
in https://github.com/kotekan/kotekan/blob/cad0f9c18714549c86f0dfb1c5ed62bbd00201de/lib/core/Config.cpp#L147
, which matches a hash on a msgpack in python:
```
import umsgpack
import collections
my_dict = {'this': 'better', 'matches': 'kotekan'}
serialized = umsgpack.packb(collections.OrderedDict(sorted(my_dict.items(), key=lambda t: t[0])))
_md5 = hashlib.md5()
_md5.update(serialized)
return _md5.hexdigest()
```

At least I couldn't come up with values that cause a mismatch...

**Comment by andrerenard** [comment]
Closed by #499
