### ISSUE TITLE
Rework baseband request management

### ISSUE THREAD

**Issue by cubranic** [kotekan/kotekan#497]
Currently, `basebandReadoutManager` holds a queue of baseband requests, with a pointer to the next request waiting to be read-out and another pointing to the next request ready to be written out. By design, only one request can be processed at a time: there is a single data buffer area that is used by both readout and writeout threads, and while the readout thread is preparing the baseband data into this buffer, the writeout thread is waiting for it to complete. Similarly, the readout thread cannot process the next request until the writeout thread has completed writing the data into an HDF5 file.

The current design also seems to contain a concurrency bug (#457, only seen on the Pathfinder), where the readout thread gets past the waiting request list instead of blocking. (basebandReadoutManager:44).

Instead, I propose:
1. share the data area for multiple events (as long as there is space), by making it a bipartite circular buffer (BipBuffer)
2. the readout thread has a queue of events waiting to be processed, and reads out their baseband data into a segment of the BipBuffer if there is one available. (If there isn't, the event is errored-out and the thread moves on to the next request in its queue.)
3. when the readout thread is done with an event, it adds a write request to the writeout thread's queue. This request includes the pointer to the event's data in the BipBuffer.
4. the writeout thread processes requests in the write queue, creating the HDF file with data from the BipBuffer, and marking that data segment available when it's done.
5. there is also a list of basebandRequestStatus that is the history of all requests since Kotekan started, and is used to return the request status data by the REST API (GET to `/baseband/event-id`). Elements in the readout and writeout queues include pointers to elements in this list, so that the readout and writeout threads can update their `state`.

**Comment by cubranic** [comment]
Rough architecture diagram:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/600891/64477513-52031280-d151-11e9-9481-d27d931854c0.png">

**Comment by andrerenard** [comment]
This was closed by #519
