### ISSUE TITLE
config file parameters

### ISSUE THREAD

**Issue by cherryng** [kotekan/kotekan#5]
`num_gpu_frames: 16` is currently listed under `N2 stuff` in the config files. but it should be a global parameters, as it is required by dpdk. Suggest to move to outside of the `N2 stuff` block.

`block_size: 32` is currently under the global `gpu` block. I think it is only needed by N2 so maybe it could go under the `N2 stuff` block instead.

**Comment by andrerenard** [comment]
@cherryng do we still need this ticket?

**Comment by andrerenard** [comment]
This is an old ticket, which I don't think applies to those configs anymore because of other system changes, closing.
