### ISSUE TITLE
RFI solar transit script improvements

### ISSUE THREAD

**Issue by andrerenard** [kotekan/kotekan#500]
- [x] Move this operation into the existing rfi_reciver.py systemd script, away from the current cron job
- [x] Improve handling of solar transit drift across the year.

**Comment by nritsche** [comment]
Should this script also register it's version and config with comet?

**Comment by andrerenard** [comment]
It doesn't have a config file, and the only thing it does is call a `coco` endpoint to change a kotekan config variable.  So I don't think we need to register it, the effects of the script will already be captured.

**Comment by james-s-willis** [comment]
See #426
