### ISSUE TITLE
Include `rfi_flagged_samples` in visFrame metadata and output files

### ISSUE THREAD

**Issue by andrerenard** [kotekan/kotekan#501]
Once we turn RFI back on the`rfi_flagged_samples` in `chimeMetadata` will be set with the number of samples flagged as over the SK sigma cut.  This will either be the number of samples that would have been flagged but not zeroed, or the number of samples that were flagged *and* zeroed.  You can tell which case you are in with the `rfi_zeroed` flag also in the metadata.  It might be worth including that flag as well so people know if the realtime zeroing was enabled in a given data product at a given time.

**Comment by jrs65** [comment]
Closing some small tasks left in #537
