### ISSUE TITLE
Fix and daemonize RFI stats server

### ISSUE THREAD

**Issue by jrs65** [kotekan/kotekan#507]
We need to check that the RFI stats server works with any changes we have to the RFI system.

**Comment by jrs65** [comment]
@nritsche we tagged you for this, but can reassign if needed.

**Comment by nritsche** [comment]
Alright!
What's the RFI stats server? Maybe ` kotekan/python/scripts/rfi_receiver.py ` ?

**Comment by jrs65** [comment]
That's the one.

**Comment by nritsche** [comment]
What is there to fix on it and what are the changes to the RFI system mentioned above?

**Comment by andrerenard** [comment]
I don't think any of the changes to the RFI system will impact the `rfi_receiver` script actually.  It's mostly we want it to be a daemon.   Also it currently breaks if kotekan is restarted on all the nodes, so it would be nice if that could be fixed, possibly just by having `systemd` restart it when it crashes.

**Comment by nritsche** [comment]
Okay.Can you remind me how/where this is run at the moment?

**Comment by andrerenard** [comment]
It was run from `carillon`.  Looks like we deleted the information from the wiki, but you can see it in the history here: https://bao.chimenet.ca/wiki/index.php?title=CHIME_Correlator_Operational_Manual&oldid=59460#RFI_Receiver_Script

**Comment by andrerenard** [comment]
Closed by #533
