### ISSUE TITLE
Jenkins: speed up make

### ISSUE THREAD

**Issue by nritsche** [kotekan/kotekan#532]
@cubranic wrote:
I use ccache on my laptop to speed up builds and it works amazingly well. https://ccache.dev/manual/3.7.1.html
it just needs -DCMAKE_CXX_COMPILER_LAUNCHER=ccache in the initial invocation to cmake, and it will effectively use ccahce $CXX to build.

**Comment by cubranic** [comment]
Extra tips for setting it up for Jenkins: https://stackoverflow.com/questions/45802970/using-ccache-with-jenkins-pipeline

**Comment by jrs65** [comment]
This sounds like an awesome idea.
