### ISSUE TITLE
write RFI lost samples to archive files

### ISSUE THREAD

**Issue by nritsche** [kotekan/kotekan#537]
- [x] add to visMetadata
- [x] set/accumulate in visAccumulate
- [ ] propagate in timeDownsample
- [x] visBuffer helper routines need to copy this over
  - [x] copy_frame???
  - [x] copy_metadata
- [x] visFileArchive/visTranspose should write this out as a fraction in HDF5 dataset `flag/frac_rfi (see `flags/frac_lost`)
- [x] python metadata defs need changing to match (visbuffer.y)
- [x] add tests
  - [X] test accumulation of rfi_total
  - [x] check frac_rfi written to HDF5 files
- [ ] write dataset ID into flags too

**Comment by andrerenard** [comment]
Can we close this ticket @tristpinsm @jrs65 ?

**Comment by tristpinsm** [comment]
yeah I think so, there is a separate issue for the archiving dataset IDs
