### ISSUE TITLE
rfi_receiver.py has a hardcoded configuration

### ISSUE THREAD

**Issue by nritsche** [kotekan/kotekan#547]
This script has it's config hardcoded atm but that doesn't seem right.

It used to have access to the kotekan GPU config (ch_ansible makes sure it gets installed on carillon at /etc/kotekan/*yaml). The problem here was that this script found more than one match for a key and applied the wrong one to its own config. As a consequence this was changed to be only a hardcoded config.

Instead give a seperate config file to rfi_receiver.py or come up with a smarter way to read the values that are needed from the kotekan config.

**Comment by james-s-willis** [comment]
I have added a config file for the `rfi_receiver.py` script, see #426 .
