### ISSUE TITLE
rfi_receiver.py uses hardcoded version

### ISSUE THREAD

**Issue by nritsche** [kotekan/kotekan#548]
It should use the version tag found by `version.py` during setup.
Alternatively just replace the versioning script with `versioneer`

**Comment by james-s-willis** [comment]
What's `versioneer`? 

Also, "It should use the version tag found by version.py during setup." Can I just call `version.py` inside `rfi_receiver.py`?

**Comment by nritsche** [comment]
> What's `versioneer`?

It's what I use in most chime python repositories. Basically does the same as `version.py` but better maintained: https://github.com/warner/python-versioneer

> Also, "It should use the version tag found by version.py during setup." Can I just call `version.py` inside `rfi_receiver.py`?

I guess. But I remember it didn't "just work" when I tried.

**Comment by james-s-willis** [comment]
I've updated the script to use `versioneer`. Could you have a look at #426?
