### ISSUE TITLE
The `likely`/`unlikely` annotations are defined in five different source files

### ISSUE THREAD

**Issue by cubranic** [kotekan/kotekan#599]
We should probably only define it once in a header, rather than in each individual file.

../lib/testing/pulsarSimProcess.cpp
../lib/stages/pulsarPostProcess.cpp
../lib/stages/frbPostProcess.cpp
../lib/stages/beamformingPostProcess.cpp
../lib/hsa/hsaPulsarUpdatePhase.cpp

**Comment by nritsche** [comment]
Are they defined in `compile.h` only on linux?

**Comment by nritsche** [comment]
I'll move them to `lib/utils/BranchPrediction.hpp`
