### ISSUE TITLE
Config chime_no_output.yaml is missing dpdk/lcore_port_map

### ISSUE THREAD

**Issue by nritsche** [kotekan/kotekan#607]
This happens currently with branch develop (9bc587dff149af1b758b498b333696094f329780)

```
Failed to start kotekan with config file ../config/chime_no_output.yaml,
 error message:
The config option: lcore_port_map is required, but was not found in the path:
 /dpdk
```

**Comment by andrerenard** [comment]
This config file isn't used anymore.  We should be using `chime_science_run_no_output.yaml`, the file will be removed in #611
