### ISSUE TITLE
rfi_receiver seems not to update the metric for few minutes after rfi event was cleared

### ISSUE THREAD

**Issue by mondana** [kotekan/kotekan#609]
RFI event on Nov 22, 7:00am PT seems to suffer from RFI metric to be lagging and staying high for few minutes after the event is cleared.
![image](https://user-images.githubusercontent.com/1731211/69469701-11c23200-0d47-11ea-9c0a-fab7dc4c6bba.png)

![20191122_0700RFI_waterfall_fracloss_stats](https://user-images.githubusercontent.com/1731211/69469642-d293e100-0d46-11ea-8369-e6cf0a29cf6b.png)

**Comment by andrerenard** [comment]
I think this might have been a result of the bug that was fixed in `2019.10a`, but we should check if we still see this lag in the metrics.

**Comment by andrerenard** [comment]
This has been fixed by #605
