### ISSUE TITLE
Add valve after rfi_vis_buffer_* before RfiDropFrame

### ISSUE THREAD

**Issue by andrerenard** [kotekan/kotekan#666]
Currently `gpu_output_n2_buffer_*` has a `valve` stage before being read by `RfiDropFrame`, but the buffers ` rfi_vis_buffer_*` don't have a `valve` stage, so it's possible that back pressure in the N2 post process pipeline can cause a backup in the GPU stage resulting in a system crash.

This addresses an issue were pulsar gaiting updates causes some nodes to crash.

**Comment by jrs65** [comment]
@andrerenard I guess we need to get this ready to deploy tomorrow. I'll try and put together a patch for the config files against master, and I'll try to get it tested on one of the test nodes.

**Comment by jrs65** [comment]
Oh, actually my mistake. I'd forgotten (again) that we don't need to deploy this tomorrow. I'll try and make a patch now anyway.
