### ISSUE TITLE
python: kotekan.ring_buffer.Reader module

### ISSUE THREAD

**Issue by nritsche** [kotekan/kotekan#692]
Add support for the new ring buffer (#686 ) on the python side.

- has a method that returns a visbuffer.VisRaw style object
- only update what has changed, rather than copying over the the full buffer every time

![shm(2)](https://user-images.githubusercontent.com/2536635/76663424-1d2baa00-653e-11ea-9f01-acf7ed65f84f.png)

@anjakefala @jrs65 please leave feedback on the drawing

How would this be used by the brokers? Here's some options:
- via `__getitem__`. internally a copy of the buffer is kept and updated on every call
- `read()`. Copy updates and return a copy of the whole buffer
- `update()`. Returns only parts of the buffer that changed

**Comment by nritsche** [comment]
- provide view of ring buffer (doesn't make sense, processing time is ~40min):
  - view(n_time_slots : int)
  - still_valid() -> bool


**This is what we decided to do:**
- only copy out `n` last time samples:
  - `read_last(n : int) -> visRaw`
  - `read_new_since(timestamp) -> visRaw`
   - keep internal copy of these to reuse on next call

**Comment by jrs65** [comment]
@nritsche @anjakefala I just thought of one thing that didn't make it into the structural data (or maybe it shouldn't go in there, but we do want it). I think we discussed having a field that the writer would use to tell the readers if it's running or not, that way kotekan can indicate to the brokers that it's shut down and to not expect any more data to arrive.

Do you think we still need this one?

**Comment by nritsche** [comment]
Sounds nice. How about a timestamp instead, so it's robust during writer crashes as well?

**Comment by jrs65** [comment]
Great. @anjakefala and myself discussed adding it, but I wasn't paying enough attention to see it hadn't got to your diagram.

How does the timestamp work? The reader just waits until a certain amount of time has passed before deciding it is dead? What if there is genuinely no data coming into kotekan for a certain amount of time (e.g. the X engine is down), but the writer process is still running and ready to go as soon as it gets data again.

**Comment by nritsche** [comment]
The reader could check that timestamp before it looks for an update. If the timestamp didn't change, the reader doesn't need to look further and can come back after some time, periodically checking for the timestamp.

**Comment by anjakefala** [comment]
@jrs65 That slipped my mind Richard, thanks for the reminder!

**Comment by anjakefala** [comment]
This has been added!
