### ISSUE TITLE
Rename "pulsar beamformer" to "tracking beamformer"

### ISSUE THREAD

**Issue by andrerenard** [kotekan/kotekan#800]
Currently the tracking beamformer is called things like the "pulsar beamformer", "pulsar beams", etc.  While there are beams and processing steps dedicated to the puslar backend, the overall system is used by a number of different backends - leading to some naming confusion.

**Comment by andrerenard** [comment]
@emmanuelfonseca @cubranic See this and #808

**Comment by cubranic** [comment]
If #808 is the PR that implements this issue, and it has been merged, does it mean that this issue can be closed?

**Comment by andrerenard** [comment]
I was waiting for the `coco` changes to also be merged.  They are here: https://github.com/chime-experiment/coco/pull/216

**Comment by cubranic** [comment]
PR to use  chime-experiment/coco#215, once it's merged: CHIME-Pulsar-Timing/ch_psr_gains#7

**Comment by andrerenard** [comment]
Closed by #808
