### ISSUE TITLE
CI: SIGILL in test_transpose.py::test_transpose

### ISSUE THREAD

**Issue by nritsche** [kotekan/kotekan#819]
test_transpose.py::test_transpose started failing with SIGILL in kotekan. We added an option to run the test through gdb to get a backtrace in #818. The problem did not appear anymore when it's ran in gdb. It also doesn't appear when ran in a tmate session. So we left the test wrapped in gdb for now (06b47a7). This should be reverted once the problem is truly solved.

[log.txt](https://github.com/kotekan/kotekan/files/5170318/log.txt)

**Comment by andrerenard** [comment]
Shouldn't this be: `test_accumulate.py/accumulate_data` ?

**Comment by nritsche** [comment]
> Shouldn't this be: `test_accumulate.py:accumulate_data` ?

Good catch. It did happen in both of them at some point: https://github.com/kotekan/kotekan/runs/1063554171
