### ISSUE TITLE
HFB metadata changes

### ISSUE THREAD

**Issue by jrs65** [kotekan/kotekan#831]
@james-s-willis I think we should just review the structures of the metadata and data before we release this time. It's going to lock in the effective data format for the foreseeable future, so we should make sure that we're happy with it. To that end I have some comments and questions.

Pasting the existing struct here for reference: 
```C
struct HFBMetadata {
    /// The ICEBoard sequence number
    int64_t fpga_seq_num;
    /// The GPS time of @c fpga_seq_num.
    struct timespec gps_time;
    /// Is GPS time accurate?
    uint32_t gps_time_flag;
    /// Frequency bin
    uint32_t freq_bin_num;
    /// Normalisation fraction
    float norm_frac;
    /// Number of samples integrated
    uint32_t num_samples_integrated;
    /// Number of samples expected
    uint32_t num_samples_expected;
    /// Data size of frame after compression
    uint32_t compressed_data_size;
    /// The number of beams in the data.
    uint32_t num_beams;
    /// The number of sub-frequencies in the data.
    uint32_t num_subfreq;
    /// ID of the dataset
    dset_id_t dataset_id;
};
```

- I think equivalent fields/concepts present elsewhere (in particular in `visMetadata` should have the same names and types). So:
    * `fpga_seq_num` -> `fpga_seq_start`
    * `uint32_t num_samples_integrated` -> `uint64_t fpga_seq_total`
    * `uint32_t num_samples_expected` -> `uint64_t fpga_seq_length`
    * `gps_time` -> `ctime`
    * `uint32_t freq_bin_num` -> `freq_id_t freq_id`
- What is the point of `compressed_data_size`? I don't see how that's ever really going to get used here, so I would suggest removing it.
- Again, what is `norm_frac`? My understanding is that it's derivable entirely from the num_samples_integrated/expected, so we should only store one of these sets, and the `num_samples_*` information is more precise.
- Is the `gps_time_flag` important enough to be in here? I don't think we even start CHIME unless it has a GPS so it's practically useless I think. I think it is as important here as for the visibility side (which is that it isn't).

Also tagging @andrerenard for comments in here.

**Comment by andrerenard** [comment]
@james-s-willis can this be closed now?

**Comment by jrs65** [comment]
I'm pretty sure James did address them all in the last HFB PR.
