### ISSUE TITLE
Rename metric kotekan_viswriter_write_time_seconds in documentation

### ISSUE THREAD

**Issue by nritsche** [kotekan/kotekan#840]
`lib/BaseWriter.hpp` documents the metric `kotekan_viswriter_write_time_seconds`.
The metric has been renamed to `kotekan_writer_write_time_seconds` in https://github.com/kotekan/kotekan/commit/2d0be738f629032dd4fa61c7a3ba0dd04140c375 and the documentation should be changed, too.

**Comment by nritsche** [comment]
Also
- kotekan_(vis)writer_late_frame_total
- kotekan_(vis)writer_bad_dataset_frame_total

**Comment by james-s-willis** [comment]
- [ ] I also need to update the grafana pages with the new names.

**Comment by james-s-willis** [comment]
Fixed in #848.
