### ISSUE TITLE
visAccumulate sometimes but not always inserts a gating state into output stream

### ISSUE THREAD

**Issue by jrs65** [kotekan/kotekan#919]
I think this happens because the initial dataset_id generated does not include a gatingState, but when new IDs are generated (based on a change in the incoming state) they get a dummy gatingState inserted. Fortunately the critical states list for visWriter doesn't contain gating and so things mostly work out fine.

For the file `/mnt/gong/staging/20201223T011000Z_chimestack_corr/01873247_0000.h5`, this shows the frames that have a gating state inserted:
![Unknown-36](https://user-images.githubusercontent.com/695206/105380819-2dcb9880-5bc3-11eb-8685-01fb0121c4af.png)

**Comment by james-s-willis** [comment]
Just to clarify we don't want a gating state in the output frame? So all I need to do is remove the dummy gating state when the `dataset_id` changes? @jrs65

**Comment by jrs65** [comment]
Yeah, I think it makes most sense to not have the gatingState there at all.
