### ISSUE TITLE
Run baseband as a sender-receiver framework

### ISSUE THREAD

**Issue by cubranic** [kotekan/kotekan#931]
- [x] GPU side: read out baseband into a Kotekan buffer connected to `bufferSend` stage to receiver (#927)
- [x] receiver: write receiver code
- [x] full-scale testing
- [x] evaluate if hardware upgrade is needed

**Comment by mondana** [comment]
do we need data_set_id integration?

**Comment by andrerenard** [comment]
This has been completed, and is working on the CHIME site.
