### ISSUE TITLE
Updates to baseband dump system

### ISSUE THREAD

**Issue by andrerenard** [kotekan/kotekan#990]
There are two large changes to the baseband dump system to be implemented for outriggers:

- [ ] #927 Replaces the existing NFS based baseband file dump system with one that uses the kotekan buffer send/recv framework to write files with a kotekan instance directly on the recording system.   Also removes the custom buffer for baseband readout staging and replaces it with a standard kotekan buffer.
- [ ] #969 Adds support for multi frequency streams
- [ ] Add python script to automatically convert the raw files generated by the new writer into HDF5

Both PRs have been tested and should be ready to use, however they require a bit of cleanup before merging.  The script to auto generate the HDF5 still needs to be written.

**Comment by kiyo-masui** [comment]
My understanding is that the python script for file conversion *does* exist, but needs to be improved and automated. However, we should still be able to get file in the right format for testing purposes. @chitrangpatel is that accurate?

**Comment by kiyo-masui** [comment]
### Draft testing requirements (feel free to edit):

- Throughput test. Scheduled trigger of realistic FRB-like dumps at regular intervals. Decrease interval until we no longer reliably capture all requested data. See what resuting throughput limit is.
- Astrophysical test. Check that the data from a baseband dump makes astrophysical sense. For example, by beamforming it to an NVSS source (requires valid calibration so careful with FPGA restarts). May be possible with previous test data if it exists and we can locate it. High priority to check in advance of deployment.
- Upstream safety test. Verify that the system drops data elegantly without affecting other data streams. Request dumps at an unrealistic rate to attempt to clog the system and make sure network buffers continue as they should. A careful audit of how the code deals with this is also required (by @andrerenard)
- Longest single dump test. Manually requests long dumps to determine limitations.
- Long term stress test. For a few pulsars, set baseband dump criteria such that we expect a few triggers per transit with no minimum time between triggers. Run for a few days and access.

This is going to be a lot of data. Most of it will *not* be converted to HDF5 and should be deleted at the end of the test and before the beginning of the following test.

**Comment by chitrangpatel** [comment]
> My understanding is that the python script for file conversion _does_ exist, but needs to be improved and automated. However, we should still be able to get file in the right format for testing purposes. @chitrangpatel is that accurate?

Yes, the script to convert to `h5` does exist and I have manipulated it to write out the new `h5` file to the appropriate event directory on `frb-baseband` archiver.

**Comment by chitrangpatel** [comment]
## how do we run the new conversion script automaticlly?

1. Rest server to receive request for conversion (this can happen when L4 requests a data dump for an event).
2. This server will monitor the baseband dump by communicating with `coco` (I believe this endpoint already exists)
3. Once the status of the baseband dump is complete, it will automatically  (a) start converting the files to h5 in the appropriate data directory on `frb-baseband`, (b) computing their md5sum (for registering it with datatrail) and (c) deleting the binary.

**Comment by leungcalvin** [comment]
Second, every HDF5 file must have an attribute called "index_map". This is correctly implemented in the converter but there's a typo: the "inputs" axis should be referred to as "input" not "inputs".

**Comment by leungcalvin** [comment]
Third, I noticed something new about baseband data in this release of the baseband system: In each HDF5 file there is now a new dataset called "sample_present". The lack of a "fill_value" attribute for this dataset causes an error in `baseband_analysis` here: 

https://github.com/CHIMEFRB/baseband-analysis/blob/c85ab231d9d92bba3a46ee551519ef93144029b2/baseband_analysis/core/bbdata.py#L456
![image](https://user-images.githubusercontent.com/42367504/135481018-6858d38d-904d-4f54-9d6e-2d3481b6725a.png)

which raises the question of what "sample_present" means and what to do with it (e.g. do we throw it away when concatenating over the frequency axis, take the intersection over all channels, or something else?). Tagging @andrerenard, and @chitrangpatel for interpretation and @kiyo-masui to help figure out whether changes should be made to `baseband_analysis`.

**Comment by leungcalvin** [comment]
I tinkered with some of the files that Chitrang converted on Tuesday 28 Sept 2021 and got baseband_analysis to read in the data successfully with the following modifications to the HDF5 file which should be regarded as tentative:
```python
# edits to incorporate into converter
import h5py
from baseband_analysis.core import BBData
with h5py.File('/data/user-data/calvin/baseband_test/baseband_2021031921580786_1000.h5','r+') as f:
    print(f['baseband'][0:10,0:10])
    print(list(f['baseband'].attrs))
    # every dataset must have an 'axis' attribute whose length matches shape of the dataset
    f['baseband'].attrs['axis'] = ['time','input']
    f['sample_present'].attrs['axis'] = ['time']
    
    # top level file object must have an 'index_map' attribute but with inputs->input
    f['index_map']['input'] = f['index_map']['inputs'][:]

    f['sample_present'].attrs['fill_value'] = False # if I set this, things work.
    #print(f['sample_present'].attrs)
    print(f['baseband'][0:10,0:10])
    print(f['index_map']['inputs'])
d1=BBData.from_acq_h5('/data/user-data/calvin/baseband_test/baseband_2021031921580786_1000.h5') # should work, calvin fixed this
```

**Comment by leungcalvin** [comment]
![image](https://user-images.githubusercontent.com/42367504/135731416-33fd056a-d981-4133-903f-c4a827adda61.png)

We see a source! Here is code to reproduce it:

```python
from glob import glob
import numpy as np
from ch_util import tools
import datetime

from baseband_analysis.core import BBData
from baseband_analysis.analysis.beamform import tied_array
from baseband_analysis.core import signal
from baseband_analysis.pipelines.config import (
 chime_backend,
 freq_id_from_filename,
 get_event_date,
 tone_backend,
)

import baseband_analysis.core.calibration as cal
from baseband_analysis.dev.vlbi import target_picker
from baseband_analysis.core.bbdata import concatenate
from baseband_analysis.analysis import beamform


from baseband_analysis.pipelines.config import chime_backend
from ch_util.ephemeris import lsa,unix_to_datetime

# I do not like that the nearest gains file is from 5 days away. 

n2_cal_h5 = '/data/chime/daily_gain_solutions/hdf5_files/gain_20210314T033635.916657Z_taua_ref_cyga_timing.h5'


def chunked(seq, size):
    return (seq[pos : pos + size] for pos in range(0, len(seq), size))

# read in first data to find 1) correlator inputs and 2) what RA we are looking at
filenames = glob('/data/chime/baseband/raw/baseband_raw/baseband_raw_2021031921580786/*.h5')
d0 = BBData.from_acq_h5(filenames[0])
chime_inputs = tools.get_correlator_inputs(unix_to_datetime(d0['time0']['ctime'])[0], correlator='FCC')

filenames.sort(key=lambda x: freq_id_from_filename(x))

transit_ra = lsa(d0['time0']['ctime'])
target_picker(transit_ra,catalog_path='/home/calvin/nvss.dat',max_targets = 20)

gains = cal.read_gains(n2_cal_h5)
datas = []

# hard coded from the output of target_picker
ra_center = 27.123670
dec_center = 53.545500
ra_offset=np.arange(-4,4,step = 0.5)
dec_offset=np.arange(-4,4,step = 0.5)
ra_offset,dec_offset = np.meshgrid(ra_offset,dec_offset)

ra = ra_offset.flat + np.float64(ra_center)
dec= dec_offset.flat + np.float64(dec_center)

# do a big loop over chunks of raw baseband files
for files in chunked(filenames[-16:], 8):
    print(
     f'{datetime.datetime.now().strftime("%Y%m%dT%H%M%S")}: Processing freq_ids: {[freq_id_from_filename(f) for f in files]}'
    )
    data = BBData.from_acq_h5(files)
    # print(f'Applying canned gains from CHIME calibration...')
    cal.apply_calibration(data, gains, inputs=chime_inputs)
    # print(f'{datetime.now().strftime("%Y%m%dT%H%M%S")}: Using tied_array beamformer...')
    static_phase_center = tools.ArrayAntenna(
     id=-1, slot=-1, powered=True, flag=True, pos=[0, 0, 0], delay=0
    )
    beamform.tied_array(
     data,
     ra=ra,
     dec=dec,
     correlator_inputs=chime_inputs,
     reference_feed=static_phase_center,
    )
    # print(f'Deleting the large raw data[\'baseband\'] dataset to free up precious RAM')
    # print(f'But hold onto the dataset object itself for use later')
    del data["baseband"]
    datas.append(data)
    
# concatenate over frequency axis
beamformed = concatenate(datas)

# calculate power, downsample, and plot the sky map
signal.tiedbeam_baseband_to_power(beamformed,time_downsample_factor = 39062, dedisperse = False, time_shift=False)
f,axs = subplots(nrows=1,ncols=2)
f.suptitle('summed over 400-406 MHz; grid spacing = 0.5 deg')
axs[0].imshow(np.nanmean(beamformed['tiedbeam_power'][:,0::2,0],axis=0).reshape(16,16))
axs[1].imshow(np.nanmean(beamformed['tiedbeam_power'][:,1::2,0],axis=0).reshape(16,16))
```

**Comment by leungcalvin** [comment]
### Detailed Test Plan
> ### Draft testing requirements (feel free to edit):
> * Longest single dump test. Manually requests long dumps to determine limitations.
> * Astrophysical test. Check that the data from a baseband dump makes astrophysical sense. For example, by beamforming it to an NVSS source (requires valid calibration so careful with FPGA restarts). May be possible with previous test data if it exists and we can locate it. High priority to check in advance of deployment.
The following dumps serve as tests of the above.
[] Check value of `max_dump_samples`, is it possible to set this to ~700 ms (~10^6 samples) for this test? How high can we go?
[] Dump `max_dump_samples` during primary N^2 calibrator transit.
[] Dump  `max_dump_samples` during B0329 pass (period of 700 ms)

> * Throughput test. Scheduled trigger of realistic FRB-like dumps at regular intervals. Decrease interval until we no longer reliably capture all requested data. See what resuting throughput limit is.
> * Upstream safety test. Verify that the system drops data elegantly without affecting other data streams. Request dumps at an unrealistic rate to attempt to clog the system and make sure network buffers continue as they should. A careful audit of how the code deals with this is also required (by @andrerenard)
To test the above, we should monitor network buffers during and in between the following tests.
[] 10 ms dump, 1 minute cadence between dumps x 11 dumps. This has worked in the past and should work again.
[] 100 ms dump, 1 minute cadence between dumps x 11 dumps. Might be harder.
[] 10 ms dump, 6 second cadence between dumps x 11 dumps. This will be hard in a different way.
[] 100 ms dump, 6 second cadence between dumps x 11 dumps. This will be very hard and might break the system at some point. Check upstream safety simultaneously.
> * Long term stress test. For a few pulsars, set baseband dump criteria such that we expect a few triggers per transit with no minimum time between triggers. Run for a few days and check that there were no dropped frames.
[] 100 ms dump, 6 second cadence between dumps x 11 dumps x 3 days. 
> This is going to be a lot of data. Most of it will _not_ be converted to HDF5 and should be deleted at the end of the test and before the beginning of the following test.

**Comment by andrerenard** [comment]
We have decided to prevent the system from allowing drops in the middle of a dump, but simply stopping a dump short if we get a full buffer condition.  This also involves preventing the `bufferSend` stage from dropping data, at the moment this isn't possible without fully disabling drops in all cases (including the receiver being down).  This will be fixed with #1000 and a configuration change.

**Comment by leungcalvin** [comment]
Here's a list of data we've taken so far. Things live on `/data/baseband_raw/baseband_raw_{event_id}` on `cfdn9`.
20211019194600: Failed due to max files open, maybe corrupt
20211019201136: Failed due to max files open, maybe corrupt
20211019205532: Succeeded, 100 ms, DM = 0
20211019210135: Succeeded, 100 ms, DM = 1000.42
20211019211629: Succeeded,  768 ms, DM = 0

**Comment by leungcalvin** [comment]
Comparison of baseband dump system when converter is running (~15:00) vs converter not running (~15:55)
![image](https://user-images.githubusercontent.com/42367504/138165040-24255825-a45f-44ae-9b5f-aa95b5d9c871.png)

**Comment by leungcalvin** [comment]
Results of preliminary baseband data offline analysis:
1) Crab GP visible
![image](https://user-images.githubusercontent.com/42367504/138346475-934e53cf-c8c7-43e4-b9ec-913c559646ca.png)
2) Some data is NaN'd out -- this is expected due to `samples_present` temporal clipping
![image](https://user-images.githubusercontent.com/42367504/138346677-106e280f-23f2-420e-b8e3-2642075de894.png)
3) The duration of the valid data in a channel (I have manually checked 3 files) matches what you expect from the raw data, e.g. there are 10752 valid frames for `freq_id = 877`, consistent with the above.
![image](https://user-images.githubusercontent.com/42367504/138347174-60d39fe7-6150-44c8-b018-008930f44008.png)
4) There is one weird channel that breaks the assumption that valid data is continuous along the time axis. The nan chunks seem to be 403 samples long, a number whose origin is not understood.
![image](https://user-images.githubusercontent.com/42367504/138347097-1ee84d41-70da-4c28-8171-d671918a782a.png)
![image](https://user-images.githubusercontent.com/42367504/138347552-36377cd0-b5a5-4270-a311-5bc89040e318.png)

**Comment by leungcalvin** [comment]
Tasks for Nov 29-30 Deployment
[ ] Interrupted recv down conversion logic : Every 6 hours, in the high-level script for the converter, check if there are new .data files that don't have .h5 files written with timestamps later than its corresponding .data file. If timestamps of .data is later than .h5 file and no lock file, figure out whether to append .data to .h5 or replace .h5 from scratch. Then do it. 
[ ] Memory pollution logic :

**Comment by leungcalvin** [comment]
Beamforming stuff:
```                                          
root@a9d9aa20cc94:/home/calvin/pipeline-update/baseband-analysis/baseband_analysis/pipelines# python outrigger_beamform.py 
192029686 --cal_h5 /data/chime/daily_gain_solutions/hdf5_files/gain_20211021T034953.566156Z_cyga_timing.h5 --ra 83.63307625
 --dec 22.01449328 --out_file /data/user-data/calvin/baseband_test/singlebeam_test_192029686.h5  
```

**Comment by leungcalvin** [comment]
Preparing trigger script:
`sudo su calvin` on `frb-analysis`
`cd ~/outrigger_ops`

Dump now: 
`./schedule-calibrator-baseband five_min --print-command -t chime -L 0.01 -d`
20211128215214

Dump B0329 when it transits:
`./schedule-calibrator-baseband B0329 --print-command -t chime -L 0.7 -d # careful, this is a long one!`

**Comment by leungcalvin** [comment]
```
python outrigger_beamform.py 200216395 --cal_h5 /data/chime/daily_gain_solutions/hdf5_files/gain_20211128T045301.074177Z_casa_ref_cyga_timing.h5 --ra 15.1571389 --dec 55.5258333 --out_file /data/user-data/calvin/baseband_test/singlebeam_test_200216395.h5
```

**Comment by chitrangpatel** [comment]
> 

@leungcalvin shouldn't the RA of `B1508+55` be closer to 225 degrees? You are providing `15.157` (probably in hours not degrees).

**Comment by leungcalvin** [comment]
Nice catch, Chitrang! Thanks so much for doing that--saved us hours of work. 

Nans: 0 Pulsars: 1!
![image](https://user-images.githubusercontent.com/42367504/143948231-8b970979-6d90-48dd-9aee-f6a2a64208b0.png)


![image](https://user-images.githubusercontent.com/42367504/143948163-71d3e8d5-31fe-4335-a5a0-093ca000c653.png)
